name: Preview HTML on Pull Requests
on:
  pull_request:
    branches:
    - feature/workflow
    paths:
    - '**.html'
  push:
    branches:
    - feature/workflow
    paths:
    - '**.html'
env:
  LINKS: nothing
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'feature/workflow'
    - uses: Azure/docker-login@v1
      with:
        login-server: tbsacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - run: |
        docker build -f ./docker/Dockerfile . -t tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
        docker push tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
      
    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: tbs-prod-aks
        resource-group: tbs-prod-rg
        
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          kubernetes/covid-19-guidance-deployment.yaml
          kubernetes/covid-19-guidance-service.yaml
        images: |
          tbsacr.azurecr.io/covid-19-guidance:${{ github.sha }}
        namespace: |
          covid-19-guidance

    # Grab a list of changed files to preview (HTML)
    - uses: lots0logs/gh-action-get-changed-files@2.1.4
      id: printing
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        paths: '*.html'
        format: space-delimited
    - name: Printing
      run: |
        ./.github/workflows/parse-file-array.sh

    #- name: Test
    #  run: |
    #    echo ${{ env.LINKS }}
    
    # Create comment in the PR with the urls of the changed files
    - name: Update status to Waiting for approval
      uses: geekodour/gh-actions-custom-status@v0.0.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LAST_COMMIT_SHA: ${{ github.event.client_payload.LAST_COMMIT_SHA }}
      with:
        args:
          --state=pending
          --context=preview-links
          --description=${{ env.LINKS }}